### ISSUE TITLE
Version not showing

### ISSUE THREAD

**Issue by HeavyTony2** [conda-forge/xyzservices-feedstock#19]
I can't tell if this is an issue with the conda recipe or with the source code upstream.

```
bokeh 3.1.1 has requirement xyzservices>=2021.09.1, but you have xyzservices 0.0.0.
Tests failed for pyload-ng-0.5.0b3.dev69-pyhf91719a_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for pyload-ng-0.5.0b3.dev69-pyhf91719a_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: pyload-ng-0.5.0b3.dev69-pyhf91719a_0.conda

```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=708750&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by martinfleis** [comment]
Upstream issue caused by improper switch from `versioneer` to `setuptools_scm`. Will push a fix today. Thanks!

```
In [1]: import xyzservices

In [2]: xyzservices.__version__
Out[2]: '0.0.0'
```

**Comment by martinfleis** [comment]
Should be fixed now. Thanks for the report!

**Comment by philippjfr** [comment]
Thank you @martinfleis!
